CREATE TABLE "patients" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" text DEFAULT 'default-org' NOT NULL,
	"clinic_id" text DEFAULT 'default-clinic' NOT NULL,
	"created_by_user_id" text NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"date_of_birth" text NOT NULL,
	"age" integer,
	"gender" text NOT NULL,
	"phone" text NOT NULL,
	"email" text,
	"address_line1" text,
	"address_line2" text,
	"city" text,
	"state" text,
	"pincode" text,
	"blood_group" text,
	"marital_status" text,
	"preferred_language" text DEFAULT 'English',
	"mrn" text NOT NULL,
	"aadhar_number" text,
	"abha_id" text,
	"insurance_provider" text,
	"insurance_policy_number" text,
	"insurance_group_number" text,
	"insurance_validity" text,
	"tpa_name" text,
	"emergency_contact_name" text,
	"emergency_contact_relationship" text,
	"emergency_contact_phone" text,
	"allergies" text[],
	"chronic_conditions" text[],
	"specialty" text DEFAULT 'General Medicine',
	"notes" text,
	"status" text DEFAULT 'Active',
	"total_visits" integer DEFAULT 0,
	"last_visit_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "patients_mrn_unique" UNIQUE("mrn")
);
--> statement-breakpoint
CREATE INDEX "patients_org_clinic_idx" ON "patients" USING btree ("org_id","clinic_id");