
import React from 'react';

interface PatientSummaryFooterProps {
  profileData?: {
    name: string;
  };
}

const PatientSummaryFooter = ({ profileData }: PatientSummaryFooterProps) => {
  return (
    <div className="bg-gradient-to-r from-blue-50 via-indigo-50 to-slate-50 border border-blue-200 rounded-xl p-3 mt-4">
      <div className="text-center space-y-1.5">
        <p className="text-[10px] text-gray-400 font-inter">
          {new Date().toLocaleString()} • {profileData?.name || "Dr. Ramakant Deshpande"}
        </p>
        <p className="text-[10px] text-gray-500 leading-relaxed font-inter">
          <strong>Disclaimer:</strong> This record is generated by the doctor in consultation with the patient. AI suggestions are not a substitute for clinical judgment.
        </p>
        <p className="text-[9px] text-gray-400 font-inter">Digital copy powered by One TheraCure • www.onetheracure.com</p>
      </div>
    </div>
  );
};

export default PatientSummaryFooter;
